services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  auth:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./imports/:/opt/keycloak/data/import:ro
      - ./src/main/resources/themes/1t-bonnes-pratiques/:/opt/keycloak/themes/1t-bonnes-pratiques
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'
